baseURL: 'https://tuansonnn.github.io/resource-tagging-workshop'
languageCode: 'en-us'
title: 'Resource Tagging Automation Workshop'
theme: 'hugo-theme-learn'

params:
  version: '1.0'
  editPage: true
  author: 'TuanSonnn'
  showVisitedLinks: true